### ISSUE TITLE
Create a new template fails

### ISSUE THREAD

**Issue by priamai** [nsano-rururu/elastalert-server_praeco_docker-compose_sample#1]
Hi there,
I am not sure whether should I ask for help, so please let me know if I have to report it elsewhere. You are the most knowledgable person I know.

Steps to reproduce:

1. clone your repository
2. perform docker build with clean cache followed by docker up
3. log into Kibana and load the sample data with web logs
4. Go to Praeco and click on create new template (see first screenshot)
5. Enable http destination for a quick test (see second screenshot)
6. Click Save
7. Observe Template not found and many errors on the web console (see third screenshot)
8. Read the docker logs from praeco I observe a template not found

Let me know if you can replicate or if this is a known bug.
Thanks you very much in advance.

New Template:
![image](https://user-images.githubusercontent.com/57333254/103475943-87515c00-4da9-11eb-9e81-c21603223609.png)

Destination
![image](https://user-images.githubusercontent.com/57333254/103475957-a354fd80-4da9-11eb-9cf9-e4aabd1217d5.png)

Errors:
![image](https://user-images.githubusercontent.com/57333254/103475972-bec00880-4da9-11eb-90f7-88ec5b40ea8e.png)

Docker log error:
```

elastalert      | 09:54:18.126Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
kibana           | {"type":"response","@timestamp":"2021-01-03T09:54:29Z","tags":["api"],"pid":7,"method":"get","statusCode":200,"req":{"url":"/api/status","method":"get","headers":{"user-agent":"curl/7.29.0","host":"localhost:5601","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":200,"responseTime":31,"contentLength":9},"message":"GET /api/status 200 31ms - 9.0B"}
elastalert      | 09:54:30.880Z ERROR elastalert-server: TemplatesController:  Failed to _findTemplate(test) error: undefined
elastalert      | template resolved
elastalert      | 09:54:30.898Z ERROR elastalert-server: TemplatesController:  Failed to _findTemplate(test) error: undefined
elastalert      | template resolved
elastalert      | 09:54:30.900Z ERROR elastalert-server:
elastalert      |     Routes:  Request for '/templates/:id' failed with error: 
elastalert      |     
elastalert      |      TypeError: Cannot read property 'write' of undefined
elastalert      |         at Object.edit (/opt/elastalert-server/src/controllers/templates/index.js:87:26)
elastalert      |         at /opt/elastalert-server/src/handlers/templates/id/post.js:16:16
elastalert      | 09:54:30.971Z ERROR elastalert-server: TemplatesController:  Failed to _findTemplate(test) error: undefined
elastalert      | template resolved
elastalert      | 09:54:30.981Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/templates'.
elastalert      | 09:54:48.402Z  INFO elastalert-server: Routes:  Successfully handled GET request for '/'.
```

**Comment by nsano-rururu** [comment]
It feels harassing to raise multiple issues for the same person and the same thing.

**Comment by priamai** [comment]
I assumed they were unrelated, it is not intentional.

**Comment by nsano-rururu** [comment]
I see, that's fine.

**Comment by nsano-rururu** [comment]
This issue will be closed as it will be managed by praeco's issue.
